
                <li>
                    <label for="mobile_number"><?php echo $this->__('Mobile Number') ?></label>
                    <div class="input-box">
                        <input type="text" name="mobile_number" id="mobile_number" value="<?php echo $this->escapeHtml($this->getFormData()->getMobileNumber()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Mobile Number')) ?>" class="input-text" />
                    </div>
                </li>
